[package]
name = "sol-template-shared"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
arrayref = "0.3.6"
borsh = "0.9.0"
solana-program = "1.7.3"

[dev-dependencies]

[lib]
crate-type = ["cdylib", "lib"]
